"""隔离级别决策 GNN 的公共接口。"""

from .graph import IsolationGraph, NodeLayout, globalize_relation_edges
from .loss import DecisionLoss, decision_loss
from .model import (
    DecisionHead,
    DecisionOutputs,
    IsolationDecisionNetwork,
    NodeEncoder,
    RecurrentRelationalProcessor,
)
from .relations import DEFAULT_RELATIONS, RELATION_ENDPOINTS
from .veristrong_data import (
    ConstraintConstructionError,
    DbcopHeader,
    DbcopHistory,
    DependencyEdges,
    Event,
    HistoryFormatError,
    Session,
    Transaction,
    TransactionAccess,
    VeriStrongProblem,
    WRChoice,
    WWChoice,
    compute_transaction_accesses,
    construct_veristrong_problem,
    export_problem_json,
    parse_dbcop_history,
    problem_summary,
)
from .veristrong_checkpoint import (
    CHECKPOINT_FORMAT,
    LoadedVeriStrongCheckpoint,
    load_veristrong_checkpoint,
    save_veristrong_checkpoint,
)
from .veristrong_cache import (
    CachedLabeledVeriStrongHistoryDataset,
    CachedLabeledVeriStrongSample,
    NORMALIZER_CACHE_FORMAT,
    SAMPLE_CACHE_FORMAT,
    load_cached_veristrong_normalizer,
    normalizer_cache_path,
    save_cached_veristrong_normalizer,
    veristrong_dataset_cache_key,
    veristrong_sample_cache_key,
)
from .veristrong_dataset import (
    LabeledVeriStrongHistoryDataset,
    LabeledVeriStrongSample,
    VeriStrongHistoryDataset,
    VeriStrongSample,
    collate_labeled_veristrong_samples,
    collate_veristrong_samples,
    discover_dbcop_histories,
)
from .veristrong_decode import (
    DecodeResult,
    DecodeStatus,
    WitnessValidation,
    decode_with_beam,
    materialize_assignment,
    scores_from_outputs,
    validate_witness,
)
from .veristrong_graph import (
    VERISTRONG_RELATION_ENDPOINTS,
    VERISTRONG_RELATIONS,
    VeriStrongGraph,
    VeriStrongNodeLayout,
    build_veristrong_graph,
    collate_veristrong_graphs,
)
from .veristrong_loss import (
    VeriStrongLoss,
    VeriStrongTargets,
    build_veristrong_targets,
    collate_veristrong_targets,
    veristrong_decision_loss,
)
from .veristrong_labels import (
    LABEL_FORMAT,
    LABEL_PRODUCER_LEGACY,
    LABEL_PRODUCER_VALIDATED_WITNESS,
    LABEL_PRODUCER_VERISTRONG_MODEL,
    VeriStrongLabels,
    labels_from_witness,
    load_veristrong_labels,
    problem_fingerprint,
    save_veristrong_labels,
)
from .veristrong_solver_model import (
    SolverTheoryVariable,
    VeriStrongModelError,
    VeriStrongSolverModel,
    labels_from_veristrong_model,
    load_veristrong_solver_model,
    parse_veristrong_model_text,
)
from .veristrong_model import (
    VeriStrongChoiceHead,
    VeriStrongDecisionNetwork,
    VeriStrongOutputs,
)
from .veristrong_normalize import VeriStrongFeatureNormalizer

__all__ = [
    "DEFAULT_RELATIONS",
    "CHECKPOINT_FORMAT",
    "NORMALIZER_CACHE_FORMAT",
    "SAMPLE_CACHE_FORMAT",
    "LABEL_FORMAT",
    "LABEL_PRODUCER_LEGACY",
    "LABEL_PRODUCER_VALIDATED_WITNESS",
    "LABEL_PRODUCER_VERISTRONG_MODEL",
    "RELATION_ENDPOINTS",
    "VERISTRONG_RELATION_ENDPOINTS",
    "VERISTRONG_RELATIONS",
    "ConstraintConstructionError",
    "CachedLabeledVeriStrongHistoryDataset",
    "CachedLabeledVeriStrongSample",
    "DbcopHeader",
    "DbcopHistory",
    "DecodeResult",
    "DecodeStatus",
    "DecisionHead",
    "DecisionLoss",
    "DecisionOutputs",
    "IsolationDecisionNetwork",
    "IsolationGraph",
    "LabeledVeriStrongHistoryDataset",
    "LabeledVeriStrongSample",
    "LoadedVeriStrongCheckpoint",
    "DependencyEdges",
    "Event",
    "HistoryFormatError",
    "NodeEncoder",
    "NodeLayout",
    "RecurrentRelationalProcessor",
    "Session",
    "SolverTheoryVariable",
    "Transaction",
    "TransactionAccess",
    "VeriStrongChoiceHead",
    "VeriStrongDecisionNetwork",
    "VeriStrongGraph",
    "VeriStrongFeatureNormalizer",
    "VeriStrongHistoryDataset",
    "VeriStrongLoss",
    "VeriStrongLabels",
    "VeriStrongModelError",
    "VeriStrongNodeLayout",
    "VeriStrongOutputs",
    "VeriStrongProblem",
    "VeriStrongSample",
    "VeriStrongSolverModel",
    "VeriStrongTargets",
    "WRChoice",
    "WWChoice",
    "WitnessValidation",
    "build_veristrong_graph",
    "build_veristrong_targets",
    "collate_veristrong_graphs",
    "collate_veristrong_targets",
    "collate_labeled_veristrong_samples",
    "collate_veristrong_samples",
    "compute_transaction_accesses",
    "construct_veristrong_problem",
    "decode_with_beam",
    "decision_loss",
    "discover_dbcop_histories",
    "export_problem_json",
    "globalize_relation_edges",
    "labels_from_witness",
    "labels_from_veristrong_model",
    "load_veristrong_checkpoint",
    "load_cached_veristrong_normalizer",
    "load_veristrong_labels",
    "load_veristrong_solver_model",
    "materialize_assignment",
    "parse_dbcop_history",
    "parse_veristrong_model_text",
    "normalizer_cache_path",
    "problem_summary",
    "problem_fingerprint",
    "save_veristrong_checkpoint",
    "save_cached_veristrong_normalizer",
    "save_veristrong_labels",
    "scores_from_outputs",
    "validate_witness",
    "veristrong_dataset_cache_key",
    "veristrong_sample_cache_key",
    "veristrong_decision_loss",
]
